version: '3'
services:
  search_engine:
    image: search-engine:test
    container_name: search_engine
    build:
      context: ./search_engine/
    ports:
      - 80:3000
    privileged: true
    tty: true
    volumes:
      - ./search_engine/:/var/www/go/src/search_engine_project/search_engine/
    environment:
      ENV: production
  crawler:
    image: crawler:test
    container_name: crawler
    build:
      context: ./crawler/
    privileged: true
    tty: true
    volumes:
      - ./crawler/:/var/www/go/src/search_engine_project/crawler/
    engironment:
      ENV: production
