DROP TABLE IF EXISTS words;
CREATE TABLE words (
  id int NOT NULL AUTO_INCREMENT,
  word VARCHAR(255) NOT NULL,
  part_of_speech VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);
